### ISSUE TITLE
Tracking issues for removing the `newlib` feature

### ISSUE THREAD

**Issue by mkroening** [hermit-os/kernel#1168]
We should get C application support on par with the Rust application support and remove most special cases for C.

- [x] https://github.com/hermit-os/kernel/pull/656
- [x] https://github.com/hermit-os/kernel/pull/1165
- [ ] https://github.com/hermit-os/kernel/pull/1166
- [x] https://github.com/hermit-os/kernel/pull/1169
- [ ] Remove semaphore

**Comment by mkroening** [comment]
I believe recursive mutexes and semaphores are necessary for Newlib for now. All special cases have been removed; the feature is now a well-behaved, properly additive feature, I think.
